name: SourceField GitHub Workflow

on:
  pull_request:
    types: [opened, synchronize]

env:
  SOURCEFIELD_LICENSE_KEY: ${{ secrets.SOURCEFIELD_LICENSE_KEY }}

jobs:
  initialComment:
    name: Post initial PR Comment (calculating...)
    runs-on: ubuntu-latest
    steps:
      - name: Update or create PR comment
        run: |
          curl -s -X POST \
          -H "Content-Type: application/json" \
          -d '{ "query": "mutation { prCommentRiskScorePending(pr: {repoOwner: \"${{ github.event.repository.owner.login }}\", repoName: \"${{ github.event.repository.name }}\", prNumber: ${{ github.event.pull_request.number }} }) }" }' \
          https://sourcefield-api.dev.streamdal.com/graphql

  fetchLanguages:
    name: Fetch Languages in Repo
    runs-on: ubuntu-latest
    outputs:
      python: ${{ steps.get-present-languages.outputs.PYTHON }}
      java: ${{ steps.get-present-languages.outputs.JAVA }}
      typescript: ${{ steps.get-present-languages.outputs.TYPESCRIPT }}
      go: ${{ steps.get-present-languages.outputs.GO }}
    steps:
      - name: Check out repo (full history)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
      - name: Get languages from extensions of changed files
        id: get-present-languages
        run: |
          git diff --name-only origin/${{ github.base_ref }}...${{ github.event.pull_request.head.sha }} \
          | rev | cut -d. -f1 | rev | sort | uniq |
          while IFS= read -r extension; do
            case "$extension" in
            py | cgi | fcgi | gyp | gypi | lmi | py3 | pyde | pyi | pyp | pyt | pyw | rpy | smk | spec | tac | wsgi | xpy)
              echo "Some Python files changed (${extension})"
              echo "PYTHON=1" >> $GITHUB_OUTPUT
              ;;
            java | jav | jsh)
              echo "Some Java files changed (${extension})"
              echo "JAVA=1" >> $GITHUB_OUTPUT
              ;;
            ts | cts | mts | tsx | js | _js | bones | cjs | es | es6 | frag | gs | jake | javascript | jsb | jscad | jsfl | jslib | jsm | jspre | jss | jsx | mjs | njs | pac | sjs | ssjs | xsjs | xsjslib)
              echo "Some TS/JS files changed (${extension})"
              echo "TYPESCRIPT=1" >> $GITHUB_OUTPUT
              ;;
            go)
              echo "Some go files changed (${extension})"
              echo "GO=1" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "No parseable language detected for extension: ${extension}"
              ;;
            esac
          done

  getMergeBase:
    name: Get Merge Base
    runs-on: ubuntu-latest
    outputs:
      merge_base: ${{ steps.get-merge-base.outputs.MERGE_BASE }}
    steps:
      - name: Check out repo (full history)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
      - name: Get merge-base
        id: get-merge-base
        run: echo "MERGE_BASE=$(git merge-base origin/${{ github.base_ref }} HEAD)" >> $GITHUB_OUTPUT

  parsePython:
    name: Parse Python Maps
    runs-on: ubuntu-latest
    container:
      image: "us-docker.pkg.dev/plumbr/sourcefield-public/lsif-python-pyright:e854776"
    needs:
      - fetchLanguages
      - getMergeBase
    if: needs.fetchLanguages.outputs.python == '1'
    steps:
      - name: Check out repo (full history)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Run LSIF parser on base ref
        run: |
          git -c advice.detachedHead=false checkout ${{ needs.getMergeBase.outputs.merge_base }}
          lsif-python index --project-name="${{ github.repository }}" --output="lsif-output-base.json"
      - name: Upload map for base commit
        uses: actions/upload-artifact@v3
        with:
          name: map-base-python
          path: lsif-output-base.json
          retention-days: 1
      - name: Run LSIF parser on head ref
        run: |
          git -c advice.detachedHead=false checkout ${{ github.event.pull_request.head.sha }}
          lsif-python index --project-name="${{ github.repository }}" --output="lsif-output-head.json"
      - name: Upload map for head commit
        uses: actions/upload-artifact@v3
        with:
          name: map-head-python
          path: lsif-output-head.json
          retention-days: 1

  parseTypeScript:
    name: Parse TypeScript and JavaScript Maps
    runs-on: ubuntu-latest
    container:
      image: "us-docker.pkg.dev/plumbr/sourcefield-public/sourcefield-lsif-typescript:d8ea8cb"
    needs:
      - fetchLanguages
      - getMergeBase
    if: needs.fetchLanguages.outputs.typescript == '1'
    steps:
      - name: Check out repo (full history)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Run LSIF parser on base ref
        run: |
          git -c advice.detachedHead=false checkout ${{ needs.getMergeBase.outputs.merge_base }}
          lsif-typescript index --explicit-implicit-loop --output="lsif-output-base.json"
      - name: Upload map for base commit
        uses: actions/upload-artifact@v3
        with:
          name: map-base-typescript
          path: lsif-output-base.json
          retention-days: 1
      - name: Run LSIF parser on head ref
        run: |
          git -c advice.detachedHead=false checkout ${{ github.event.pull_request.head.sha }}
          lsif-typescript index --explicit-implicit-loop --output="lsif-output-head.json"
      - name: Upload map for head commit
        uses: actions/upload-artifact@v3
        with:
          name: map-head-typescript
          path: lsif-output-head.json
          retention-days: 1

  parseJava:
    name: Parse Java Maps
    runs-on: ubuntu-latest
    container:
      image: "us-docker.pkg.dev/plumbr/sourcefield-public/sourcefield-lsif-java:0adeb7c"
    needs:
      - fetchLanguages
      - getMergeBase
    if: needs.fetchLanguages.outputs.java == '1'
    steps:
      - name: Check out repo (full history)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Run LSIF parser on base ref
        run: |
          git -c advice.detachedHead=false checkout ${{ needs.getMergeBase.outputs.merge_base }}
          java \
          -Dlog4j.configurationFile=file:/sourcefield/src/log4j2.xml \
          -jar /sourcefield/target/sourcefield-lsif-java-1.0-SNAPSHOT-jar-with-dependencies.jar \
          -d="${PWD}" -o="${PWD}/lsif-output-base.json"
      - name: Upload map for base commit
        uses: actions/upload-artifact@v3
        with:
          name: map-base-java
          path: lsif-output-base.json
          retention-days: 1
      - name: Run LSIF parser on head ref
        run: |
          git -c advice.detachedHead=false checkout ${{ github.event.pull_request.head.sha }}
          java \
          -Dlog4j.configurationFile=file:/sourcefield/src/log4j2.xml \
          -jar /sourcefield/target/sourcefield-lsif-java-1.0-SNAPSHOT-jar-with-dependencies.jar \
          -d="${PWD}" -o="${PWD}/lsif-output-head.json"
      - name: Upload map for head commit
        uses: actions/upload-artifact@v3
        with:
          name: map-head-java
          path: lsif-output-head.json
          retention-days: 1

  parseGo:
    name: Parse Go Maps
    runs-on: ubuntu-latest
    container:
      image: "us-docker.pkg.dev/plumbr/sourcefield-public/sourcefield-lsif-go:6bd6e8a"
    needs:
      - fetchLanguages
      - getMergeBase
    if: needs.fetchLanguages.outputs.go == '1'
    steps:
      - name: Check out repo (full history)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Run LSIF parser on base ref
        run: |
          git -c advice.detachedHead=false checkout ${{ needs.getMergeBase.outputs.merge_base }}
          lsif-go --output="lsif-output-base.json"
      - name: Upload map for base commit
        uses: actions/upload-artifact@v3
        with:
          name: map-base-go
          path: lsif-output-base.json
          retention-days: 1
      - name: Run LSIF parser on head ref
        run: |
          git -c advice.detachedHead=false checkout ${{ github.event.pull_request.head.sha }}
          lsif-go --output="lsif-output-head.json"
      - name: Upload map for head commit
        uses: actions/upload-artifact@v3
        with:
          name: map-head-go
          path: lsif-output-head.json
          retention-days: 1

  processMapsPython:
    name: Process and Diff Maps (Python)
    runs-on: ubuntu-latest
    container:
      image: "us-docker.pkg.dev/plumbr/sourcefield-public/parse-processor/lsif-processor:6b34720"
    needs:
      - fetchLanguages
      - getMergeBase
      - parsePython
    steps:
      - name: Check out repo (full history)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Set ownership
        # see https://github.com/actions/runner/issues/2033
        run: chown -R $(id -u):$(id -g) $PWD
      - name: Download base map
        uses: actions/download-artifact@v3
        with:
          name: map-base-python
      - name: Run parse processor on base map
        run: |
          git -c advice.detachedHead=false checkout ${{ needs.getMergeBase.outputs.merge_base }}
          grep -rn "^\s*# ::> " . > /possible_annotations.txt || true
          cd /sourcefield
          python3 -m processor.python \
          --filename="${GITHUB_WORKSPACE}/lsif-output-base.json" \
          - run \
          --write_to_file=True \
          --map_output_file="/sourcefield/base.pickle"
      - name: Download head map
        uses: actions/download-artifact@v3
        with:
          name: map-head-python
      - name: Run parse processor on head map
        run: |
          git -c advice.detachedHead=false checkout ${{ github.event.pull_request.head.sha }}
          grep -rn "^\s*# ::> " . > /possible_annotations.txt || true
          cd /sourcefield
          python3 -m processor.python \
          --filename="${GITHUB_WORKSPACE}/lsif-output-head.json" \
          - run \
          --write_to_file=True \
          --map_output_file="/sourcefield/head.pickle"
      - name: Get diff
        run: |
          git diff origin/${{ github.base_ref }}...${{ github.event.pull_request.head.sha }} > /sourcefield/diff.txt
          ls -lah /sourcefield
      - name: Diff maps and report metrics to backend
        run: |
          cd /sourcefield
          python3 -m processor.mapdiff.commands - diff_maps_and_report_metrics \
          --language="PYTHON" \
          --map1=/sourcefield/base.pickle \
          --map2=/sourcefield/head.pickle \
          --diff=/sourcefield/diff.txt \
          --pr_event="${GITHUB_EVENT_PATH}" \
          --backend_url="https://sourcefield-api.dev.streamdal.com/graphql"

  processMapsTypeScript:
    name: Process and Diff Maps (TypeScript and JavaScript)
    runs-on: ubuntu-latest
    container:
      image: "us-docker.pkg.dev/plumbr/sourcefield-public/parse-processor/lsif-processor:6b34720"
    needs:
      - fetchLanguages
      - getMergeBase
      - parseTypeScript
    steps:
      - name: Check out repo (full history)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Set ownership
        # see https://github.com/actions/runner/issues/2033
        run: chown -R $(id -u):$(id -g) $PWD
      - name: Download base map
        uses: actions/download-artifact@v3
        with:
          name: map-base-typescript
      - name: Run parse processor on base map
        run: |
          git -c advice.detachedHead=false checkout ${{ needs.getMergeBase.outputs.merge_base }}
          grep -rn "^\s*# ::> " . > /possible_annotations.txt || true
          cd /sourcefield
          python3 -m processor.python \
          --filename="${GITHUB_WORKSPACE}/lsif-output-base.json" \
          - run \
          --write_to_file=True \
          --map_output_file="/sourcefield/base.pickle"
      - name: Download head map
        uses: actions/download-artifact@v3
        with:
          name: map-head-typescript
      - name: Run parse processor on head map
        run: |
          git -c advice.detachedHead=false checkout ${{ github.event.pull_request.head.sha }}
          grep -rn "^\s*# ::> " . > /possible_annotations.txt || true
          cd /sourcefield
          python3 -m processor.python \
          --filename="${GITHUB_WORKSPACE}/lsif-output-head.json" \
          - run \
          --write_to_file=True \
          --map_output_file="/sourcefield/head.pickle"
      - name: Get diff
        run: |
          git diff origin/${{ github.base_ref }}...${{ github.event.pull_request.head.sha }} > /sourcefield/diff.txt
          ls -lah /sourcefield
      - name: Diff maps and report metrics to backend
        run: |
          cd /sourcefield
          python3 -m processor.mapdiff.commands - diff_maps_and_report_metrics \
          --language="TS_JS" \
          --map1=/sourcefield/base.pickle \
          --map2=/sourcefield/head.pickle \
          --diff=/sourcefield/diff.txt \
          --pr_event="${GITHUB_EVENT_PATH}" \
          --backend_url="https://sourcefield-api.dev.streamdal.com/graphql"

  processMapsJava:
    name: Process and Diff Maps (Java)
    runs-on: ubuntu-latest
    container:
      image: "us-docker.pkg.dev/plumbr/sourcefield-public/parse-processor/lsif-processor:6b34720"
    needs:
      - fetchLanguages
      - getMergeBase
      - parseJava
    steps:
      - name: Check out repo (full history)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Set ownership
        # see https://github.com/actions/runner/issues/2033
        run: chown -R $(id -u):$(id -g) $PWD
      - name: Download base map
        uses: actions/download-artifact@v3
        with:
          name: map-base-java
      - name: Run parse processor on base map
        run: |
          git -c advice.detachedHead=false checkout ${{ needs.getMergeBase.outputs.merge_base }}
          grep -rn "^\s*# ::> " . > /possible_annotations.txt || true
          cd /sourcefield
          python3 -m processor.python \
          --filename="${GITHUB_WORKSPACE}/lsif-output-base.json" \
          - run \
          --write_to_file=True \
          --map_output_file="/sourcefield/base.pickle"
      - name: Download head map
        uses: actions/download-artifact@v3
        with:
          name: map-head-java
      - name: Run parse processor on head map
        run: |
          git -c advice.detachedHead=false checkout ${{ github.event.pull_request.head.sha }}
          grep -rn "^\s*# ::> " . > /possible_annotations.txt || true
          cd /sourcefield
          python3 -m processor.python \
          --filename="${GITHUB_WORKSPACE}/lsif-output-head.json" \
          - run \
          --write_to_file=True \
          --map_output_file="/sourcefield/head.pickle"
      - name: Get diff
        run: |
          git diff origin/${{ github.base_ref }}...${{ github.event.pull_request.head.sha }} > /sourcefield/diff.txt
          ls -lah /sourcefield
      - name: Diff maps and report metrics to backend
        run: |
          cd /sourcefield
          python3 -m processor.mapdiff.commands - diff_maps_and_report_metrics \
          --language="JAVA" \
          --map1=/sourcefield/base.pickle \
          --map2=/sourcefield/head.pickle \
          --diff=/sourcefield/diff.txt \
          --pr_event="${GITHUB_EVENT_PATH}" \
          --backend_url="https://sourcefield-api.dev.streamdal.com/graphql"

  processMapsGo:
    name: Process and Diff Maps (Go)
    runs-on: ubuntu-latest
    container:
      image: "us-docker.pkg.dev/plumbr/sourcefield-public/parse-processor/lsif-processor:6b34720"
    needs:
      - fetchLanguages
      - getMergeBase
      - parseGo
    steps:
      - name: Check out repo (full history)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Set ownership
        # see https://github.com/actions/runner/issues/2033
        run: chown -R $(id -u):$(id -g) $PWD
      - name: Download base map
        uses: actions/download-artifact@v3
        with:
          name: map-base-go
      - name: Run parse processor on base map
        run: |
          git -c advice.detachedHead=false checkout ${{ needs.getMergeBase.outputs.merge_base }}
          grep -rn "^\s*# ::> " . > /possible_annotations.txt || true
          cd /sourcefield
          python3 -m processor.python \
          --filename="${GITHUB_WORKSPACE}/lsif-output-base.json" \
          - run \
          --write_to_file=True \
          --map_output_file="/sourcefield/base.pickle"
      - name: Download head map
        uses: actions/download-artifact@v3
        with:
          name: map-head-go
      - name: Run parse processor on head map
        run: |
          git -c advice.detachedHead=false checkout ${{ github.event.pull_request.head.sha }}
          grep -rn "^\s*# ::> " . > /possible_annotations.txt || true
          cd /sourcefield
          python3 -m processor.python \
          --filename="${GITHUB_WORKSPACE}/lsif-output-head.json" \
          - run \
          --write_to_file=True \
          --map_output_file="/sourcefield/head.pickle"
      - name: Get diff
        run: |
          git diff origin/${{ github.base_ref }}...${{ github.event.pull_request.head.sha }} > /sourcefield/diff.txt
          ls -lah /sourcefield
      - name: Diff maps and report metrics to backend
        run: |
          cd /sourcefield
          python3 -m processor.mapdiff.commands - diff_maps_and_report_metrics \
          --language="GO" \
          --map1=/sourcefield/base.pickle \
          --map2=/sourcefield/head.pickle \
          --diff=/sourcefield/diff.txt \
          --pr_event="${GITHUB_EVENT_PATH}" \
          --backend_url="https://sourcefield-api.dev.streamdal.com/graphql"

  finalize:
    name: Finalize metrics
    runs-on: ubuntu-latest
    container:
      image: "us-docker.pkg.dev/plumbr/sourcefield-public/parse-processor/lsif-processor:6b34720"
    needs:
      - fetchLanguages
      - getMergeBase
      - processMapsPython
      - processMapsTypeScript
      - processMapsJava
      - processMapsGo
    if: ${{ always() }}
    steps:
      - name: Create score card
        run: |
          cd /sourcefield
          python3 -m processor.mapdiff.commands - create_score_card \
          --pr_event="${GITHUB_EVENT_PATH}" \
          --merge_base_sha=${{ needs.getMergeBase.outputs.merge_base }} \
          --head_sha=${{ github.event.pull_request.head.sha }} \
          --backend_url="https://sourcefield-api.dev.streamdal.com/graphql"
